# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f380957e3c69daed597d226af2b66c03191abd5c86f1d97f8912495cd5740178050461211c4d84c8f6adb51819ee3bc2239f6bd3a1cdd113f2f7dc1b4de8dc1f

test:
  secret_key_base: 57019a5a4f0cf7abae0ef52f4818a3d47a8bdd8a9ebcc56dc99203ebe06808365354d9bc2f897ab217759be54bd9a9ee64608bd956368cee10bf401ddeb32f32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
